### PR TITLE
Add std.interprocess to the standard library

### PR DESCRIPTION
**Pull request by RazvanN7**
## Description 

The goal of this project is to implement a flexible interprocess data structure, synchronization and communication library.
An equivalent library in C++ is Boost Interprocess.
The important goal would be to port all the features from boost.interprocess to D.

## What are rough milestones for this project 

- default and custom allocators to operate on shm
- named IPC primitives: shm, semaphores, spinlock, mutex, condvar, barriers
- standard containers like vector, deque, list, string, set that operates on shm
- message queue on shm without relying on the kernel for data transfer
- managed shared memory
- IPC smart pointers

## Expected outcome

A module - `std.interprocess` - merged in the standard library.

## Recommended Skills

Basic D language skills
Understanding of IPC mechanisms and other operating systems concepts
Experience with C++

## Potential mentors

@burner 

## Get started

Boost Interprocess - https://www.boost.org/doc/libs/1_69_0/doc/html/interprocess.html

### CODE REVIEW

**Comment by Emmankoko** [comment]
Has this project been worked on?

**Comment by RazvanN7** [comment]
@Emmankoko Not as far as I know.

**Comment by Emmankoko** [comment]
@RazvanN7 Noted!

**Comment by Emmankoko** [comment]
Is the project being submitted by someone for GSOC?

**Comment by RazvanN7** [comment]
We are currently applying for GSOC, so we hope someone will choose to work on it!

**Comment by RazvanN7** [comment]
@Emmankoko I don't know whether you are enrolled at any university program, but if you are, you should consider applying to GSOC (assuming we do get selected as an organization to participate).

**Comment by Emmankoko** [comment]
@RazvanN7 I just completed my bachelors in computer science and I was also part of the most recent SAOC 23 doing STL interop. I'm still working on it an hope to get it done soon. so if there's a chance to work on this project, I'll give it a thought! how flexible is GSOC by the way?

**Comment by RazvanN7** [comment]
@Emmankoko I think they might be flexible. First, let's see if we get selected and then we can sort out the details. Also, we can chat about this in more depth on slack or discord to not pollute this PR with tangential discussions.

**Pull request merged**
